name: Build Action
on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: true
        type: string
      build-command:
        description: 'Build command to execute'
        required: false
        type: string
        default: 'npm run build'
      artifact-name:
        description: 'Name for the uploaded artifacts'
        required: false
        type: string
        default: 'node-app-artifacts'
      artifact-path:
        description: 'Path to upload as artifacts'
        required: false
        type: string
        default: '.'
      retention-days:
        description: 'Number of days to retain artifacts'
        required: false
        type: number
        default: 7

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        id: run-build
        run: ${{ inputs.build-command }} || echo "Build command failed, stop..."
        continue-on-error: false
      
      - name: Upload artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: ${{ inputs.retention-days }}

      - name: Build summary
        if: always()
        run: |
          echo "## Build Results Summary" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.run-build.outcome }}" == "success" ]; then
            echo "✅ Build completed successfully" >> $GITHUB_STEP_SUMMARY
            echo "- Artifacts uploaded: ${{ inputs.artifact-name }}" >> $GITHUB_STEP_SUMMARY
            echo "- Retention period: ${{ inputs.retention-days }} days" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Build completed with warnings or errors" >> $GITHUB_STEP_SUMMARY
            echo "- Check build logs for details" >> $GITHUB_STEP_SUMMARY
          fi 