name: Reusable Node.js Build Workflow

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: true
        type: string
    outputs:
      build-status:
        description: 'Status of the build job'
        value: ${{ jobs.build.outputs.build-status }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.set-output.outputs.build-status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        id: run-build
        run: npm run build || true # Placeholder; continues if no build script
        continue-on-error: true

      - name: Set build status
        id: set-output
        run: |
          if [ ${{ steps.run-build.outcome }} == "success" ]; then
            echo "build-status=success" >> $GITHUB_OUTPUT
          else
            echo "build-status=failure" >> $GITHUB_OUTPUT
          fi